### ISSUE TITLE
i cant change the settings

### ISSUE THREAD

**Issue by GhostCodeByte** [soulsoiledit/geode-finder#2]
if i start the programm for windows than it just search for the pree defind seed and i cant change the settings
thank you man for this program

**Comment by soulsoiledit** [comment]
What do you mean by can't change the settings? Have you set the command line argument flags?

**Comment by GhostCodeByte** [comment]
sry i'm stubit but what is rust

**Comment by GhostCodeByte** [comment]
i dont know why but if i start the .exe that is in the zip file its instanly starts the search with a seed and i cant change it like i want maby i make sth wrong pls tell me

**Comment by soulsoiledit** [comment]
You will need to use the program from the command line if you wish to change the settings.

**Comment by GhostCodeByte** [comment]
Ok thanks but how can I run the code in windows or do I need linux

**Comment by soulsoiledit** [comment]
You can call the .exe from the command line using `./filename.exe [arguments].`

**Comment by GhostCodeByte** [comment]
ok thanks men
