### ISSUE TITLE
Negative seed error

### ISSUE THREAD

**Issue by Sicktek** [soulsoiledit/geode-finder#3]
geode-finder.exe -v "1.20" -s "-660667041762483759"
error: unexpected argument '-6' found

**Comment by soulsoiledit** [comment]
Use `-s=-660667041762483759` to use negative seeds in the meantime, or wait for the next release.

**Comment by giustinorossi** [comment]
how can I change any defaults information? if i write something like  geode-finder.exe -v "1.19" -s=-1244788433206992640, it starts searching for geodes.

**Comment by soulsoiledit** [comment]
Fixed in latest release.
