### ISSUE TITLE
Starting Coordinates for search

### ISSUE THREAD

**Issue by tehfireburnz** [soulsoiledit/geode-finder#6]
Is there any way to configure the starting coordinates of the search? I don't want to search anywhere around spawn but maybe starting at a specific x and z coordinate. Let's just for arguments sake say my base is at x=3,00,000, y=1,000,000, that's a distance of ~3,162,277 blocks (197.5k chunks) from spawn. Now I want to search a 10,000 chunk radius around my base for a viable high density location, so I would have to put r=207500 ? If that's the case, so much wasted time searching areas which are not in interest.

**Comment by soulsoiledit** [comment]
I've added this feature in the latest release! Make sure to input the values in terms of chunk coordinates.

**Comment by tehfireburnz** [comment]
Wow! What a quick turnaround. Awesome work. One minor note, it will not accept a negative starting x or z chunk into it, at least on the windows release... attached
![image](https://github.com/soulsoiledit/geode-finder/assets/143775791/fed8d121-a4d6-4400-b4b5-0439fb4e3f1d)

**Comment by soulsoiledit** [comment]
Ah, that was a silly mistake on my part. The newest release should have that problem fixed.
